apiVersion: apps/v1
kind: Deployment
metadata:
  name: daaschooser
  labels:
    app: daaschooser
spec:
  replicas: 2
  selector:
    matchLabels:
      app: daaschooser
  template:
    metadata:
      labels:
        app: daaschooser
    spec:
      containers:
      - name: daaschooser
        image: daaschooser:latest  # Update this with your registry path
        imagePullPolicy: Always
        ports:
        - containerPort: 4173
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: daaschooser
  labels:
    app: daaschooser
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: daaschooser 